*** Variables ***
${tops_uat_url}    https://uat.tops.co.th/en/
${email_login_info}    nuk6395@gmail.com
${password_login_info}    Nuk639597899
${expected_product_description}    Express delivery is not applicable to this product.
${expected_already_account_txt}    Already have an account? Login
${incorrect_email_info}    nuk6395gmail.com
${expected_register_email_error}    You have entered an invalid email
${register_success_expected_EN_txt}    Just one last step!Please check your email to activate your account.
${maximum_wait_time}    10s
${register_success_expected_TH_txt}    ถึงขั้นตอนสุดท้ายแล้ว!กรุณาเช็คอีเมลเพื่อยืนยันการสมัคร
